orgs:
  baloise:
    admins:
    - b013329
    - b014651
    - baopso
    - christiansiegel
    - culmat
    - danielgrob
    - eloy83
    - erleiuat
    - FabrizioBroennimann
    - frank-baier
    - greg-junkietech
    - hirsch88
    - joachimprinzbach
    - jochenpilger
    - jordilaforge
    - luechtdiode
    - MarkusTiede
    - MichaelLewi
    - michelpfirter
    - mistel28
    - niiku
    - Pascal1968
    - patrickhusi
    - patrit
    - pbracher
    - PhilippeDePesseroy
    - ralfzurich
    - ricomeyer
    - sbubendorf
    - schlijo
    - seejaybee
    - Solaflex
    - StefanHolmstock
    - ThomasSchoeb
    - tklueber
    - UrsBienz
    - WolfgangWo
    billing_email: Group.CH_Open-Source@baloise.ch
    company: ""
    default_repository_permission: read
    description: Open Source @ Baloise Group
    email: Group.CH_Open-Source@baloise.ch
    has_organization_projects: true
    has_repository_projects: true
    location: Aeschengraben 21, 4002 Basel, Switzerland
    members:
    - 6f1045
    - abrjak
    - AlainLatscha
    - Alex-Thoma
    - aMiladinovic
    - arburk
    - ArthurNeudeck
    - b016533
    - BeateGuldenschuh
    - BenjaminMueller84
    - bhaskarchenchu
    - borisrudolf
    - bsolar17
    - CookieMonster70
    - CorsinSulser
    - dalchers
    - Dalchi
    - DanielPrill
    - davidloeffler82
    - DennisBannerman
    - dinupoker
    - Dr-Tech81
    - dweber019
    - ErmacoraGregor
    - Flapmax
    - Gagne87
    - Georges52
    - geschbach
    - Ginious
    - harry08
    - HeikoDammeyer
    - HeinzKauer
    - hhenkel
    - honeggera
    - janbrohl
    - JeanDoescher
    - JelenaSretenovic 
    - klaushuberruiz
    - krzmur
    - kullmanp
    - l0r5
    - lagoaresti
    - LaurentSteiner
    - lazaki
    - lbiry
    - leubedane
    - m4rc0z
    - marcellobellini
    - MarkusFlorian79
    - mariusreusch
    - matal0
    - mbobzin
    - mfredenhagen
    - MicBag
    - mikevader
    - mk-it-easy
    - mladenplaninicic
    - monkold
    - MrCode97
    - mw-solutions
    - nfricker
    - nobilo
    - NoraKurzbein
    - OlgaSchwarz
    - olivierglath
    - r3dDoX
    - raltho
    - randeep228
    - renat1sakenov
    - reneschatz
    - Rikdewinne
    - RMarLuce
    - rolfstebler
    - rotalf
    - rothmarco
    - sauterl
    - simonboerlin
    - skytime-sh
    - sobabufe
    - stefan-jungo
    - stefanschoe
    - StephanSST
    - svene
    - thbert
    - Thomas4712
    - ThomasPBurri
    - Tiliavir
    - TimonLoew
    - tommuelli
    - trichie
    - tschneichel
    - vangual
    - VasilijeRadulovic
    - yannickholzenkamp
    - YvesVdm
    - RCBiczok
    - oleg-arch
    - prevosys
    members_can_create_repositories: true
    name: Baloise Group
    teams:
      Alumni:
        description: Former member of the Baloise Open Source Group
        maintainers:
        - baopso
        members:
        - RCBiczok
        - r3dDoX
        - sauterl
        - hhenkel
        - renat1sakenov
        - mfredenhagen
        - MrCode97
        - nfricker
        privacy: closed
      CICD pipeline:
        description: ""
        maintainers:
        - culmat
        - danielgrob
        - niiku
        - joachimprinzbach
        members:
        - vangual
        - Solaflex
        - renat1sakenov
        - CookieMonster70
        - bhaskarchenchu
        - randeep228
        - matal0
        privacy: closed
        repos:
          CICD-pipeline: write
          CICD-pipeline-private: write
          WorkflowLibs-archive: read
          cicd-pipeline_java-maven-jboss-hello-world: admin
          jenkins-shared-library-archive: read
      Developers:
        description: Baloise Developers
        maintainers:
        - niiku
        - b014651
        members:
        - olivierglath
        - simonboerlin
        privacy: closed
        repos:
          gitopscli: read
          orchestra-maven-plugin: admin
          ui-library-next: read
      Open Source:
        description: all (known) Baloise Group GitHub members
        maintainers:
        - tklueber
        - culmat
        - danielgrob
        - niiku
        - MarkusTiede
        - luechtdiode
        - joachimprinzbach
        - schlijo
        - frank-baier
        - patrickhusi
        - baopso
        - hirsch88
        - eloy83
        - patrit
        - greg-junkietech
        - jordilaforge
        - seejaybee
        - christiansiegel
        - erleiuat
        - michelpfirter
        - WolfgangWo
        - ralfzurich
        - b014651
        - jochenpilger
        - ThomasSchoeb
        - UrsBienz
        - Pascal1968
        - sbubendorf
        - StefanHolmstock
        - MichaelLewi
        - mistel28
        - ricomeyer
        members:
        - svene
        - vangual
        - mikevader
        - dweber019
        - sauterl
        - janbrohl
        - StephanSST
        - kullmanp
        - Solaflex
        - HeinzKauer
        - marcellobellini
        - MicBag
        - harry08
        - trichie
        - Ginious
        - bsolar17
        - Tiliavir
        - yannickholzenkamp
        - renat1sakenov
        - tommuelli
        - Dalchi
        - mw-solutions
        - mk-it-easy
        - NoraKurzbein
        - AlainLatscha
        - leubedane
        - monkold
        - m4rc0z
        - TimonLoew
        - l0r5
        - BeateGuldenschuh
        - borisrudolf
        - CookieMonster70
        - abrjak
        - tschneichel
        - mladenplaninicic
        - Gagne87
        - rotalf
        - DennisBannerman
        - dinupoker
        - stefanschoe
        - VasilijeRadulovic
        - davidloeffler82
        - 6f1045
        - klaushuberruiz
        - honeggera
        - ThomasPBurri
        - reneschatz
        - HeikoDammeyer
        - MarkusFlorian79
        - lbiry
        - JeanDoescher
        - Rikdewinne
        - CorsinSulser
        - ErmacoraGregor
        - Alex-Thoma
        - arburk
        - DanielPrill
        - Thomas4712
        - RMarLuce
        - BenjaminMueller84
        - dalchers
        - olivierglath
        - skytime-sh
        - mbobzin
        - geschbach
        - simonboerlin
        - b016533
        - raltho
        - rothmarco
        - krzmur
        - Georges52
        - thbert
        - lagoaresti
        - Dr-Tech81
        - ArthurNeudeck
        - YvesVdm
        - sobabufe
        - LaurentSteiner
        - OlgaSchwarz
        - stefan-jungo
        - rolfstebler
        - matal0
        - prevosys
        privacy: closed
        repos:
          CICD-pipeline: admin
          CICD-pipeline-private: admin
          CLX-BKDOCIX: admin
          HelloGit: admin
          WorkflowLibs-archive: read
          baloise-bootstrap: admin
          baloise.github.io: write
          code-of-gotham: admin
          dashboard-plus: write
          digital-signature: write
          eZooKeeper: admin
          egitblit: write
          gitopscli: write
          goldcards: write
          importthem: write
          intellij-plugin-stencil-web-components: read
          java: read
          jay: write
          jee6-playground: write
          jenkins-maven-plugin: write
          jenkins-shared-library-archive: read
          jira-plus: write
          oom: admin
          open-source: write
          orchestra-maven-plugin: admin
          pitches: write
          pm-analysen: write
          proxy: admin
          rocket-chat-notifier: admin
          stripe2paypal: write
          test-automation-framework: write
          ui-library-next: write
          utils: write
          ws-itsec_owasp: write
        teams:
          CM_Monitoring:
            description: Members driving the monitoring-community content
            maintainers:
            - culmat
            - MarkusTiede
            - greg-junkietech
            - b014651
            privacy: closed
            repos:
              CICD-pipeline: admin
              CICD-pipeline-private: admin
              CLX-BKDOCIX: admin
              HelloGit: admin
              WorkflowLibs-archive: read
              baloise-bootstrap: admin
              baloise.github.io: write
              code-of-gotham: admin
              dashboard-plus: write
              digital-signature: write
              eZooKeeper: admin
              egitblit: write
              gitopscli: write
              goldcards: write
              importthem: write
              intellij-plugin-stencil-web-components: read
              java: read
              jay: write
              jee6-playground: write
              jenkins-maven-plugin: write
              jenkins-shared-library-archive: read
              jira-plus: write
              oom: admin
              open-source: write
              orchestra-maven-plugin: admin
              pitches: write
              pm-analysen: write
              proxy: admin
              rocket-chat-notifier: admin
              stripe2paypal: write
              test-automation-framework: write
              ui-library-next: write
              utils: write
              ws-itsec_owasp: write
          IT-CH_Bets:
            description: IT Innovationsteam (Bets)
            maintainers:
            - jordilaforge
            - jochenpilger
            members:
            - mk-it-easy
            - NoraKurzbein
            - mladenplaninicic
            - RMarLuce
            privacy: closed
            repos:
              CICD-pipeline: admin
              CICD-pipeline-private: admin
              CLX-BKDOCIX: admin
              HelloGit: admin
              WorkflowLibs-archive: read
              baloise-bootstrap: admin
              baloise.github.io: write
              code-of-gotham: admin
              dashboard-plus: write
              digital-signature: write
              eZooKeeper: admin
              egitblit: write
              gitopscli: write
              goldcards: write
              importthem: write
              intellij-plugin-stencil-web-components: read
              java: read
              jay: write
              jee6-playground: write
              jenkins-maven-plugin: write
              jenkins-shared-library-archive: read
              jira-plus: write
              oom: admin
              open-source: write
              orchestra-maven-plugin: admin
              pitches: write
              pm-analysen: write
              proxy: admin
              resteasy-test: read
              rocket-chat-notifier: admin
              stripe2paypal: write
              test-automation-framework: write
              ui-library-next: write
              utils: write
              ws-itsec_owasp: write
          IT-CH_Integration-Services:
            description: ""
            maintainers:
            - MarkusTiede
            - schlijo
            - frank-baier
            members:
            - dweber019
            - sauterl
            - StephanSST
            - Alex-Thoma
            - mbobzin
            privacy: closed
            repos:
              CICD-pipeline: admin
              CICD-pipeline-private: admin
              CLX-BKDOCIX: admin
              HelloGit: admin
              WorkflowLibs-archive: read
              baloise-bootstrap: admin
              baloise.github.io: write
              code-of-gotham: admin
              corellia: admin
              dashboard-plus: write
              digital-signature: write
              eZooKeeper: admin
              egitblit: write
              gitopscli: write
              goldcards: write
              importthem: write
              intellij-plugin-stencil-web-components: read
              java: read
              jay: write
              jee6-playground: write
              jenkins-maven-plugin: write
              jenkins-shared-library-archive: read
              jira-plus: write
              oom: admin
              open-source: write
              orchestra-maven-plugin: admin
              pitches: write
              pm-analysen: write
              proxy: admin
              resteasy-test: read
              rocket-chat-notifier: admin
              stripe2paypal: write
              test-automation-framework: write
              ui-library-next: write
              utils: write
              ws-itsec_owasp: write
          IT-CH_SECC_CM_Java:
            description: 'Software Engineering Competence Center - Community: Java
              Developers'
            maintainers:
            - tklueber
            - frank-baier
            - patrickhusi
            - sbubendorf
            members:
            - svene
            - StephanSST
            - Ginious
            - Tiliavir
            - tschneichel
            - arburk
            - DanielPrill
            - Thomas4712
            privacy: closed
            repos:
              CICD-pipeline: admin
              CICD-pipeline-private: admin
              CLX-BKDOCIX: admin
              HelloGit: admin
              WorkflowLibs-archive: read
              baloise-bootstrap: admin
              baloise.github.io: write
              code-of-gotham: admin
              dashboard-plus: write
              digital-signature: write
              eZooKeeper: admin
              egitblit: write
              gitopscli: write
              goldcards: write
              importthem: write
              intellij-plugin-stencil-web-components: read
              java: admin
              jay: write
              jee6-playground: write
              jenkins-maven-plugin: write
              jenkins-shared-library-archive: read
              jira-plus: write
              oom: admin
              open-source: write
              orchestra-maven-plugin: admin
              pitches: write
              pm-analysen: write
              proxy: admin
              resteasy-test: read
              rocket-chat-notifier: admin
              stripe2paypal: write
              test-automation-framework: write
              ui-library-next: write
              utils: write
              ws-itsec_owasp: write
          IT-CH_SECC_CM_Open-Source:
            description: 'Software Engineering Competence Center - Community: Open-Source'
            maintainers:
            - culmat
            - MarkusTiede
            - luechtdiode
            - joachimprinzbach
            - hirsch88
            - Tiliavir
            - jordilaforge
            - christiansiegel
            - arburk
            members:
            - kullmanp
            privacy: closed
            repos:
              CICD-pipeline: admin
              CICD-pipeline-private: admin
              CLX-BKDOCIX: admin
              HelloGit: admin
              WorkflowLibs-archive: read
              baloise-bootstrap: admin
              baloise.github.io: write
              code-of-gotham: admin
              dashboard-plus: write
              digital-signature: write
              eZooKeeper: admin
              egitblit: write
              gitopscli: write
              goldcards: write
              importthem: write
              intellij-plugin-stencil-web-components: read
              java: read
              jay: write
              jee6-playground: write
              jenkins-maven-plugin: write
              jenkins-shared-library-archive: read
              jira-plus: write
              oom: admin
              open-source: write
              orchestra-maven-plugin: admin
              org: admin
              pitches: write
              pm-analysen: write
              proxy: admin
              resteasy-test: read
              rocket-chat-notifier: admin
              stripe2paypal: write
              test-automation-framework: write
              ui-library-next: write
              utils: write
              ws-itsec_owasp: write
          this-or-that:
            description: Team for This-or-That
            maintainers:
            - MarkusTiede
            - hirsch88
            - jordilaforge
            members:
            - yannickholzenkamp
            privacy: closed
            repos:
              CICD-pipeline: admin
              CICD-pipeline-private: admin
              CLX-BKDOCIX: admin
              HelloGit: admin
              WorkflowLibs-archive: read
              baloise-bootstrap: admin
              baloise.github.io: write
              code-of-gotham: admin
              dashboard-plus: write
              digital-signature: write
              eZooKeeper: admin
              egitblit: write
              gitopscli: write
              goldcards: write
              importthem: write
              intellij-plugin-stencil-web-components: read
              java: read
              jay: write
              jee6-playground: write
              jenkins-maven-plugin: write
              jenkins-shared-library-archive: read
              jira-plus: write
              oom: admin
              open-source: write
              orchestra-maven-plugin: admin
              pitches: write
              pm-analysen: write
              proxy: admin
              rocket-chat-notifier: admin
              stripe2paypal: write
              test-automation-framework: write
              this-or-that: admin
              ui-library-next: write
              utils: write
              ws-itsec_owasp: write

